version: "4.5"
services:
  hub:
    image: selenium/hub:4.5
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:4.5
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:4.5
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
